"""
================================================================================
  MULTIMODAL RAG INGESTION PIPELINE — Complete Local Framework
================================================================================

AUTHOR  : Senior AI Architect (Multimodal RAG)
VERSION : 2.0.0  (+ Contextual Retrieval)

PURPOSE
-------
This script implements a fully local, free data ingestion pipeline that:
  1. Accepts ANY file type (PDF, DOCX, image, audio, video, code).
  2. Routes each file to the correct modality processor.
  3. Normalises every output into structured Markdown.
  4. Appends strict metadata headers (source, modality, timestamp).
  5. Sends the unified Markdown to a local LLM (llama3 via Ollama) for
     agentic, semantically-aware chunking, returning chunks as JSON.
  6. [NEW] Runs each chunk through ContextualRetriever, which prepends a
     situating context sentence generated by the LLM with awareness of the
     FULL document — dramatically improving dense and sparse retrieval recall.

WHAT IS CONTEXTUAL RETRIEVAL?
------------------------------
Technique introduced by Anthropic (Sept 2024).  The core insight: naive
chunking loses document-level context.  A chunk saying "The defendant was
found liable" is ambiguous in isolation — liable for WHAT, in WHICH case?

Contextual Retrieval fixes this by asking an LLM:
  "Given the WHOLE document, write a 1–2 sentence context for THIS chunk
   that a reader would need to understand it without any surrounding text."

That context sentence is then PREPENDED to the chunk before embedding.
Result: 49 % reduction in retrieval failures (Anthropic benchmark).

The full document is passed once per file; each chunk is contextualised in
a separate, lightweight LLM call (parallelised via ThreadPoolExecutor).

References
----------
  https://www.anthropic.com/news/contextual-retrieval

================================================================================
  PREREQUISITES — read BEFORE running
================================================================================

── Python libraries ────────────────────────────────────────────────────────────
  pip install docling            # PDF / DOCX → Markdown (DocumentProcessor)
  pip install openai-whisper     # Local speech-to-text  (AudioProcessor)
  pip install ollama             # Ollama Python SDK     (ImageProcessor, ChunkingAgent, ContextualRetriever)
  pip install Pillow             # Image validation      (ImageProcessor)
  pip install torch              # Required by Whisper

  One-liner:
  pip install docling openai-whisper ollama Pillow torch

── System dependencies ──────────────────────────────────────────────────────────
  FFmpeg  (VideoProcessor — frame extraction + audio demux)
    macOS  : brew install ffmpeg
    Ubuntu : sudo apt-get install ffmpeg
    Windows: https://ffmpeg.org/download.html  → add to PATH

  Ollama  (ImageProcessor + ChunkingAgent + ContextualRetriever)
    Install : https://ollama.com/download
    Pull models:
      ollama pull llava     ← multimodal vision model  (ImageProcessor)
      ollama pull llama3    ← text / reasoning model   (ChunkingAgent, ContextualRetriever)
    Start server: ollama serve   (runs on http://localhost:11434)

  Whisper models are downloaded automatically on first run.
  Docling models are downloaded automatically on first run.

================================================================================
  ARCHITECTURE — data flow  (v2.0 with Contextual Retrieval)
================================================================================

  file_path
      │
      ▼
  DataRouter.route()
      │
      ├─► DocumentProcessor  (pdf, docx, doc)
      ├─► AudioProcessor     (mp3, wav, m4a, flac, ogg)
      ├─► ImageProcessor     (jpg, jpeg, png, gif, bmp, tiff, webp)
      ├─► VideoProcessor     (mp4, avi, mov, mkv, webm)
      └─► CodeProcessor      (py, js, ts, java, c, cpp, cs, go, rs, rb, sh)
              │
              ▼
         raw Markdown
              │
              ▼
      MarkdownUnifier.unify()
              │
              ▼
         unified Markdown  ──────────────────────────────┐
         (with metadata header)                           │ (full doc
              │                                           │  kept for
              ▼                                           │  context)
      ChunkingAgent.chunk()                               │
              │                                           │
              ▼                                           │
         List[ChunkDict]                                  │
         {chunk_text, summary, keywords}                  │
              │                                           │
              ▼                                           │
      ContextualRetriever.enrich()  ◄────────────────────┘
      (parallel LLM calls, one per chunk)
              │
              ▼
         List[ChunkDict]   ← adds 'context' and 'contextualized_text'
         ready for embedding + BM25 indexing

================================================================================
"""

from __future__ import annotations

import base64
import json
import logging
import mimetypes
import os
import re
import subprocess
import tempfile
from abc import ABC, abstractmethod
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Union

# ── logging ─────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%S",
)
logger = logging.getLogger("MultimodalRAG")


# ══════════════════════════════════════════════════════════════════════════════
#  BASE PROCESSOR
# ══════════════════════════════════════════════════════════════════════════════

class BaseProcessor(ABC):
    """
    Abstract base class for all modality processors.

    Every concrete processor MUST implement `process()`, which accepts a file
    path and returns a Markdown string.  Raising `ProcessingError` on failure
    allows the pipeline to handle errors gracefully without crashing.
    """

    class ProcessingError(RuntimeError):
        """Raised when a processor cannot handle the given file."""

    @abstractmethod
    def process(self, file_path: Path) -> str:
        """
        Process *file_path* and return its content as a Markdown string.

        Parameters
        ----------
        file_path : Path
            Absolute path to the source file.

        Returns
        -------
        str
            UTF-8 Markdown representing the file's content.

        Raises
        ------
        BaseProcessor.ProcessingError
            If processing fails for any recoverable reason.
        """


# ══════════════════════════════════════════════════════════════════════════════
#  1. DOCUMENT PROCESSOR  (PDF / DOCX → Markdown via Docling)
# ══════════════════════════════════════════════════════════════════════════════

class DocumentProcessor(BaseProcessor):
    """
    Converts PDF and Word documents into Markdown using **Docling**.

    Docling is a powerful document understanding library that:
      • Preserves document structure (headings, tables, lists, captions).
      • Handles multi-column layouts and embedded figures.
      • Runs entirely locally — no API calls.

    Install : pip install docling
    Docs    : https://github.com/DS4SD/docling
    """

    def process(self, file_path: Path) -> str:
        logger.info("[DocumentProcessor] Processing '%s'", file_path.name)

        try:
            # Lazy import so the script doesn't crash if docling is absent
            # and a different processor is used.
            from docling.document_converter import DocumentConverter  # type: ignore
        except ImportError as exc:
            raise self.ProcessingError(
                "Docling is not installed. Run: pip install docling"
            ) from exc

        try:
            converter = DocumentConverter()
            result = converter.convert(str(file_path))

            # Docling's export_to_markdown() returns a clean Markdown string.
            markdown_output = result.document.export_to_markdown()

            if not markdown_output.strip():
                raise self.ProcessingError(
                    f"Docling returned empty output for '{file_path.name}'. "
                    "The file may be image-only (scanned) or encrypted."
                )

            logger.info(
                "[DocumentProcessor] Success — %d characters", len(markdown_output)
            )
            return markdown_output

        except self.ProcessingError:
            raise  # re-raise our own errors unchanged
        except Exception as exc:
            raise self.ProcessingError(
                f"Docling failed to process '{file_path}': {exc}"
            ) from exc


# ══════════════════════════════════════════════════════════════════════════════
#  2. AUDIO PROCESSOR  (audio → transcript via local Whisper)
# ══════════════════════════════════════════════════════════════════════════════

class AudioProcessor(BaseProcessor):
    """
    Transcribes audio files to Markdown using OpenAI's **Whisper** model
    running entirely on-device (CPU or CUDA GPU).

    Whisper is loaded once and cached on the instance to avoid reloading
    for each file when processing many audio tracks (e.g. video keyframes).

    Install : pip install openai-whisper torch
    Models  : tiny | base | small | medium | large  (larger = more accurate)
    Docs    : https://github.com/openai/whisper
    """

    #: Whisper model size.  "base" balances speed and accuracy for most use cases.
    DEFAULT_MODEL = "base"

    def __init__(self, model_size: str = DEFAULT_MODEL) -> None:
        self._model_size = model_size
        self._model: Any = None  # lazy-loaded on first use

    def _load_model(self) -> Any:
        """Load (and cache) the Whisper model."""
        if self._model is None:
            try:
                import whisper  # type: ignore
            except ImportError as exc:
                raise self.ProcessingError(
                    "openai-whisper is not installed. Run: pip install openai-whisper torch"
                ) from exc

            logger.info(
                "[AudioProcessor] Loading Whisper '%s' model (first run downloads it)…",
                self._model_size,
            )
            self._model = whisper.load_model(self._model_size)
            logger.info("[AudioProcessor] Whisper model loaded.")

        return self._model

    def process(self, file_path: Path) -> str:
        logger.info("[AudioProcessor] Transcribing '%s'", file_path.name)

        model = self._load_model()

        try:
            # `transcribe()` returns a dict with 'text' and 'segments'.
            # We use segments to produce timestamped Markdown.
            result = model.transcribe(
                str(file_path),
                verbose=False,          # suppress per-segment console spam
                word_timestamps=False,  # segment-level timestamps are enough
            )
        except Exception as exc:
            raise self.ProcessingError(
                f"Whisper transcription failed for '{file_path}': {exc}"
            ) from exc

        segments: list[dict] = result.get("segments", [])
        full_text: str = result.get("text", "").strip()

        if not full_text:
            raise self.ProcessingError(
                f"Whisper returned empty transcription for '{file_path.name}'. "
                "Check that the file contains speech."
            )

        # ── Format as timestamped Markdown ──────────────────────────────────
        lines = ["## Transcript\n"]

        if segments:
            for seg in segments:
                start = self._fmt_ts(seg.get("start", 0.0))
                text  = seg.get("text", "").strip()
                if text:
                    lines.append(f"**[{start}]** {text}\n")
        else:
            # Fallback: no segment info, just emit the full text
            lines.append(full_text)

        markdown_output = "\n".join(lines)
        logger.info(
            "[AudioProcessor] Success — %d segments, %d chars",
            len(segments),
            len(markdown_output),
        )
        return markdown_output

    @staticmethod
    def _fmt_ts(seconds: float) -> str:
        """Convert a float seconds value to HH:MM:SS format."""
        secs = int(seconds)
        h, rem = divmod(secs, 3600)
        m, s   = divmod(rem, 60)
        return f"{h:02d}:{m:02d}:{s:02d}"


# ══════════════════════════════════════════════════════════════════════════════
#  3. IMAGE PROCESSOR  (image → Markdown description via Ollama + LLaVA)
# ══════════════════════════════════════════════════════════════════════════════

class ImageProcessor(BaseProcessor):
    """
    Sends images to a **LLaVA** vision model running locally via **Ollama**
    and prompts it to describe visual content, transcribe handwriting, or
    convert charts/tables into Markdown.

    LLaVA (Large Language-and-Vision Assistant) is a multimodal model that
    accepts both text prompts and image inputs.

    Install : pip install ollama Pillow
    Setup   : ollama pull llava   (downloads ~4 GB model)
    Docs    : https://ollama.com/library/llava
    """

    #: Ollama model tag for vision inference.
    DEFAULT_MODEL = "llava"

    #: System-level prompt that steers LLaVA toward structured Markdown output.
    VISION_PROMPT = (
        "You are a highly accurate document analysis assistant. "
        "Examine the provided image carefully and produce output in Markdown format.\n\n"
        "Follow these rules:\n"
        "1. **Charts / graphs**: Convert data into a Markdown table. "
        "   Include axis labels, legend entries, and approximate values.\n"
        "2. **Handwritten text**: Transcribe it verbatim inside a blockquote (`> `).\n"
        "3. **Diagrams / flowcharts**: Describe each node and edge in a numbered list.\n"
        "4. **Photographs / illustrations**: Write a detailed, factual description "
        "   (2–5 sentences).\n"
        "5. **Screenshots / UI**: Describe the interface layout and any visible text.\n\n"
        "Be precise. Do NOT add commentary or apologies. Output ONLY Markdown."
    )

    def __init__(self, model: str = DEFAULT_MODEL) -> None:
        self._model = model

    def process(self, file_path: Path) -> str:
        logger.info("[ImageProcessor] Analysing '%s' with %s", file_path.name, self._model)

        try:
            import ollama  # type: ignore
        except ImportError as exc:
            raise self.ProcessingError(
                "ollama is not installed. Run: pip install ollama"
            ) from exc

        # ── Validate the image is readable ──────────────────────────────────
        try:
            from PIL import Image  # type: ignore
            with Image.open(file_path) as img:
                img.verify()   # raises on corrupt files
        except Exception as exc:
            raise self.ProcessingError(
                f"Cannot open image '{file_path.name}': {exc}"
            ) from exc

        # ── Encode image as base64 for the Ollama API ────────────────────────
        image_b64 = base64.b64encode(file_path.read_bytes()).decode("utf-8")

        # ── Call LLaVA via Ollama ────────────────────────────────────────────
        try:
            response = ollama.chat(
                model=self._model,
                messages=[
                    {
                        "role": "user",
                        "content": self.VISION_PROMPT,
                        "images": [image_b64],
                    }
                ],
            )
        except Exception as exc:
            raise self.ProcessingError(
                f"Ollama/{self._model} call failed: {exc}. "
                "Ensure 'ollama serve' is running and 'ollama pull llava' was executed."
            ) from exc

        # ── Extract text from response ───────────────────────────────────────
        markdown_output: str = response["message"]["content"].strip()

        if not markdown_output:
            raise self.ProcessingError(
                f"LLaVA returned empty description for '{file_path.name}'."
            )

        logger.info("[ImageProcessor] Success — %d chars", len(markdown_output))
        return markdown_output

    def process_bytes(self, image_bytes: bytes, label: str = "frame") -> str:
        """
        Convenience method: accept raw image bytes instead of a file path.
        Used by VideoProcessor to handle in-memory keyframes.
        """
        with tempfile.NamedTemporaryFile(suffix=".jpg", delete=False) as tmp:
            tmp.write(image_bytes)
            tmp_path = Path(tmp.name)

        try:
            return self.process(tmp_path)
        finally:
            tmp_path.unlink(missing_ok=True)


# ══════════════════════════════════════════════════════════════════════════════
#  4. VIDEO PROCESSOR  (video → audio transcript + keyframe descriptions)
# ══════════════════════════════════════════════════════════════════════════════

class VideoProcessor(BaseProcessor):
    """
    Processes video files by:
      1. Using **FFmpeg** (via subprocess) to extract the audio track.
      2. Using **FFmpeg** to extract keyframes at a configurable interval.
      3. Passing audio → AudioProcessor for transcription.
      4. Passing each keyframe → ImageProcessor for visual description.
      5. Merging both outputs into a single, timestamped Markdown document.

    System dep : FFmpeg must be on PATH
    Install    : brew install ffmpeg  /  sudo apt-get install ffmpeg
    """

    #: How often (in seconds) to sample a keyframe.
    DEFAULT_KEYFRAME_INTERVAL = 30  # one frame every 30 s

    def __init__(
        self,
        keyframe_interval: int = DEFAULT_KEYFRAME_INTERVAL,
        whisper_model: str = AudioProcessor.DEFAULT_MODEL,
        llava_model:   str = ImageProcessor.DEFAULT_MODEL,
    ) -> None:
        self._keyframe_interval = keyframe_interval
        self._audio_proc = AudioProcessor(model_size=whisper_model)
        self._image_proc = ImageProcessor(model=llava_model)

    # ── Main entry point ─────────────────────────────────────────────────────

    def process(self, file_path: Path) -> str:
        logger.info("[VideoProcessor] Processing '%s'", file_path.name)
        self._check_ffmpeg()

        sections: list[str] = [f"# Video Analysis: {file_path.name}\n"]

        with tempfile.TemporaryDirectory(prefix="rag_video_") as tmpdir:
            tmp = Path(tmpdir)

            # ── Step 1: Extract audio and transcribe ─────────────────────────
            audio_md = self._extract_and_transcribe_audio(file_path, tmp)
            sections.append("## 🔊 Audio Transcript\n")
            sections.append(audio_md)
            sections.append("\n---\n")

            # ── Step 2: Extract keyframes and describe them ───────────────────
            frame_md = self._extract_and_describe_frames(file_path, tmp)
            sections.append("## 🎞️ Visual Keyframes\n")
            sections.append(frame_md)

        markdown_output = "\n".join(sections)
        logger.info("[VideoProcessor] Success — %d chars total", len(markdown_output))
        return markdown_output

    # ── Helpers ──────────────────────────────────────────────────────────────

    def _check_ffmpeg(self) -> None:
        """Verify FFmpeg is available on the system PATH."""
        try:
            subprocess.run(
                ["ffmpeg", "-version"],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                check=True,
            )
        except (FileNotFoundError, subprocess.CalledProcessError) as exc:
            raise self.ProcessingError(
                "FFmpeg is not installed or not on PATH. "
                "Install it via your package manager or https://ffmpeg.org/download.html"
            ) from exc

    def _extract_and_transcribe_audio(self, video: Path, tmp: Path) -> str:
        """Demux audio track from video and transcribe with Whisper."""
        audio_path = tmp / "audio.wav"

        # FFmpeg flags:
        #   -vn         : disable video output
        #   -acodec pcm_s16le : standard WAV format, Whisper compatible
        #   -ar 16000   : 16 kHz sample rate (Whisper's native rate)
        #   -ac 1       : mono channel
        cmd = [
            "ffmpeg", "-y",           # overwrite without asking
            "-i", str(video),
            "-vn",
            "-acodec", "pcm_s16le",
            "-ar", "16000",
            "-ac", "1",
            "-pix_fmt", "yuv420p",
            str(audio_path),
        ]
        self._run_ffmpeg(cmd, label="audio extraction")

        try:
            return self._audio_proc.process(audio_path)
        except BaseProcessor.ProcessingError as exc:
            logger.warning("[VideoProcessor] Audio transcription failed: %s", exc)
            return "*Audio transcription unavailable.*\n"

    def _extract_and_describe_frames(self, video: Path, tmp: Path) -> str:
        """Extract keyframes and send each to LLaVA for description."""
        frames_dir = tmp / "frames"
        frames_dir.mkdir()

        # FFmpeg flags:
        #   -vf fps=1/N : one frame every N seconds
        #   %06d.jpg    : zero-padded sequential filenames
        cmd = [
            "ffmpeg", "-y",
            "-i", str(video),
            "-vf", f"fps=1/{self._keyframe_interval}",
            str(frames_dir / "%06d.jpg"),
        ]
        self._run_ffmpeg(cmd, label="keyframe extraction")

        frame_files = sorted(frames_dir.glob("*.jpg"))
        if not frame_files:
            logger.warning("[VideoProcessor] No keyframes extracted.")
            return "*No keyframes could be extracted.*\n"

        lines: list[str] = []
        for idx, frame_file in enumerate(frame_files):
            # Estimate the wall-clock timestamp of this frame
            timestamp_sec = idx * self._keyframe_interval
            ts_str = AudioProcessor._fmt_ts(float(timestamp_sec))

            lines.append(f"### Frame at {ts_str}\n")
            try:
                description = self._image_proc.process(frame_file)
                lines.append(description)
            except BaseProcessor.ProcessingError as exc:
                logger.warning("[VideoProcessor] Frame %s failed: %s", frame_file.name, exc)
                lines.append("*Frame description unavailable.*")
            lines.append("\n")

        return "\n".join(lines)

    @staticmethod
    def _run_ffmpeg(cmd: list[str], label: str) -> None:
        """Run an FFmpeg command, raising ProcessingError on failure."""
        logger.debug("[VideoProcessor] FFmpeg %s: %s", label, " ".join(cmd))
        try:
            result = subprocess.run(
                cmd,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.PIPE,
                check=True,
                timeout=600,  # 10-minute safety timeout
            )
        except subprocess.CalledProcessError as exc:
            stderr = exc.stderr.decode(errors="replace")
            raise BaseProcessor.ProcessingError(
                f"FFmpeg {label} failed:\n{stderr}"
            ) from exc
        except subprocess.TimeoutExpired as exc:
            raise BaseProcessor.ProcessingError(
                f"FFmpeg {label} timed out after 10 minutes."
            ) from exc


# ══════════════════════════════════════════════════════════════════════════════
#  5. CODE PROCESSOR  (source code → fenced Markdown code block)
# ══════════════════════════════════════════════════════════════════════════════

class CodeProcessor(BaseProcessor):
    """
    Wraps raw source-code files in a Markdown fenced code block with the
    appropriate language tag, preserving syntax for downstream LLM analysis.

    Supported extensions → language tags are defined in `EXTENSION_MAP`.
    Any unmapped extension falls back to a plain (untagged) code block.
    """

    EXTENSION_MAP: dict[str, str] = {
        ".py"   : "python",
        ".js"   : "javascript",
        ".ts"   : "typescript",
        ".java" : "java",
        ".c"    : "c",
        ".cpp"  : "cpp",
        ".cs"   : "csharp",
        ".go"   : "go",
        ".rs"   : "rust",
        ".rb"   : "ruby",
        ".sh"   : "bash",
        ".bash" : "bash",
        ".zsh"  : "bash",
        ".php"  : "php",
        ".swift": "swift",
        ".kt"   : "kotlin",
        ".r"    : "r",
        ".sql"  : "sql",
        ".html" : "html",
        ".css"  : "css",
        ".yaml" : "yaml",
        ".yml"  : "yaml",
        ".json" : "json",
        ".toml" : "toml",
        ".xml"  : "xml",
    }

    def process(self, file_path: Path) -> str:
        logger.info("[CodeProcessor] Wrapping '%s'", file_path.name)

        try:
            # Try UTF-8 first; fall back to latin-1 for legacy files
            try:
                code = file_path.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                code = file_path.read_text(encoding="latin-1")
        except OSError as exc:
            raise self.ProcessingError(
                f"Cannot read source file '{file_path}': {exc}"
            ) from exc

        lang = self.EXTENSION_MAP.get(file_path.suffix.lower(), "")

        markdown_output = (
            f"## Source File: `{file_path.name}`\n\n"
            f"```{lang}\n"
            f"{code}\n"
            f"```\n"
        )

        logger.info("[CodeProcessor] Success — %d lines", code.count("\n") + 1)
        return markdown_output


# ══════════════════════════════════════════════════════════════════════════════
#  WEB URL PROCESSOR  (web page → clean Markdown)
# ══════════════════════════════════════════════════════════════════════════════

class URLProcessor:
    """
    Fetches a web page and extracts its main readable content as Markdown.

    Uses **trafilatura**, which strips nav bars, ads, footers, and boilerplate
    and returns just the article/body text — far cleaner than raw HTML scraping.
    Falls back to a bare <p>-tag extraction if trafilatura is unavailable.

    Note: this does NOT subclass BaseProcessor because its input is a URL
    string, not a file path. The pipeline calls it via a dedicated branch.

    Install : pip install trafilatura httpx
    """

    DEFAULT_TIMEOUT = 20  # seconds

    def __init__(self, timeout: int = DEFAULT_TIMEOUT) -> None:
        self._timeout = timeout

    def process(self, url: str) -> tuple[str, str]:
        """
        Fetch *url* and return (markdown_content, page_title).

        Raises
        ------
        BaseProcessor.ProcessingError
            On network failure or empty extraction.
        """
        logger.info("[URLProcessor] Fetching '%s'", url)

        try:
            import httpx  # type: ignore
        except ImportError as exc:
            raise BaseProcessor.ProcessingError(
                "httpx is not installed. Run: pip install httpx"
            ) from exc

        # ── Fetch the raw HTML ────────────────────────────────────────────
        try:
            headers = {"User-Agent": "Mozilla/5.0 (RAG-ingest; +local)"}
            resp = httpx.get(
                url, timeout=self._timeout, follow_redirects=True, headers=headers
            )
            resp.raise_for_status()
            html = resp.text
        except Exception as exc:
            raise BaseProcessor.ProcessingError(
                f"Failed to fetch '{url}': {exc}"
            ) from exc

        # ── Extract main content with trafilatura ─────────────────────────
        title = url
        markdown = ""
        try:
            import trafilatura  # type: ignore

            extracted = trafilatura.extract(
                html,
                output_format="markdown",
                include_links=False,
                include_images=False,
                with_metadata=False,
            )
            if extracted:
                markdown = extracted
            meta = trafilatura.extract_metadata(html)
            if meta and getattr(meta, "title", None):
                title = meta.title
        except ImportError:
            logger.warning(
                "[URLProcessor] trafilatura not installed — falling back to crude extraction."
            )
            markdown = self._fallback_extract(html)
        except Exception as exc:
            logger.warning("[URLProcessor] trafilatura failed (%s) — using fallback.", exc)
            markdown = self._fallback_extract(html)

        if not markdown.strip():
            raise BaseProcessor.ProcessingError(
                f"No readable content extracted from '{url}'."
            )

        # Prefix a heading so the source page is obvious in every chunk.
        markdown_output = f"# {title}\n\nSource URL: {url}\n\n{markdown}"
        logger.info("[URLProcessor] Success — %d chars from '%s'", len(markdown_output), title)
        return markdown_output, title

    @staticmethod
    def _fallback_extract(html: str) -> str:
        """Very crude <p>/<h*> text extraction when trafilatura is missing."""
        text = re.sub(r"(?is)<(script|style|nav|footer|header).*?</\1>", " ", html)
        text = re.sub(r"(?is)</p>|</h[1-6]>|<br\s*/?>", "\n", text)
        text = re.sub(r"(?s)<[^>]+>", " ", text)            # strip remaining tags
        text = re.sub(r"[ \t]+", " ", text)
        text = re.sub(r"\n\s*\n+", "\n\n", text)
        return text.strip()


# ══════════════════════════════════════════════════════════════════════════════
#  DATA ROUTER
# ══════════════════════════════════════════════════════════════════════════════

class DataRouter:
    """
    Central file-type dispatcher.

    Given a file path, `DataRouter.route()` infers the modality (by extension
    and MIME type), instantiates the correct `BaseProcessor` subclass, and
    returns the raw Markdown output.

    Routing priority: extension map → MIME type prefix → error.
    """

    # ── Extension → processor class mapping ─────────────────────────────────
    DOCUMENT_EXTS = {".pdf", ".docx", ".doc", ".odt", ".pptx", ".ppt", ".xlsx", ".xls"}
    AUDIO_EXTS    = {".mp3", ".wav", ".m4a", ".flac", ".ogg", ".aac", ".wma", ".opus"}
    IMAGE_EXTS    = {".jpg", ".jpeg", ".png", ".gif", ".bmp", ".tiff", ".tif", ".webp", ".svg"}
    VIDEO_EXTS    = {".mp4", ".avi", ".mov", ".mkv", ".webm", ".flv", ".wmv", ".m4v"}
    CODE_EXTS     = set(CodeProcessor.EXTENSION_MAP.keys())

    def __init__(
        self,
        whisper_model: str = AudioProcessor.DEFAULT_MODEL,
        llava_model:   str = ImageProcessor.DEFAULT_MODEL,
        keyframe_interval: int = VideoProcessor.DEFAULT_KEYFRAME_INTERVAL,
    ) -> None:
        # Pre-instantiate processors to share model caches across multiple files
        self._document_proc = DocumentProcessor()
        self._audio_proc    = AudioProcessor(model_size=whisper_model)
        self._image_proc    = ImageProcessor(model=llava_model)
        self._video_proc    = VideoProcessor(
            keyframe_interval=keyframe_interval,
            whisper_model=whisper_model,
            llava_model=llava_model,
        )
        self._code_proc     = CodeProcessor()

    def route(self, file_path: str | Path) -> tuple[str, str]:
        """
        Detect the file type and dispatch to the correct processor.

        Parameters
        ----------
        file_path : str | Path
            Path to the input file.

        Returns
        -------
        tuple[str, str]
            (markdown_content, modality_label)
            where modality_label is one of:
            "Document" | "Audio" | "Image" | "Video" | "Code"

        Raises
        ------
        FileNotFoundError
            If *file_path* does not exist.
        ValueError
            If the file type is not supported.
        BaseProcessor.ProcessingError
            Propagated from the underlying processor on processing failure.
        """
        path = Path(file_path).resolve()

        if not path.exists():
            raise FileNotFoundError(f"File not found: '{path}'")

        ext      = path.suffix.lower()
        modality = self._detect_modality(path, ext)

        logger.info("[DataRouter] '%s' → %s", path.name, modality)

        processor_map: dict[str, BaseProcessor] = {
            "Document" : self._document_proc,
            "Audio"    : self._audio_proc,
            "Image"    : self._image_proc,
            "Video"    : self._video_proc,
            "Code"     : self._code_proc,
        }

        processor = processor_map[modality]
        markdown  = processor.process(path)

        return markdown, modality

    def _detect_modality(self, path: Path, ext: str) -> str:
        """Determine modality from extension, falling back to MIME type."""
        if ext in self.DOCUMENT_EXTS: return "Document"
        if ext in self.AUDIO_EXTS:    return "Audio"
        if ext in self.IMAGE_EXTS:    return "Image"
        if ext in self.VIDEO_EXTS:    return "Video"
        if ext in self.CODE_EXTS:     return "Code"

        # MIME-type fallback
        mime, _ = mimetypes.guess_type(str(path))
        if mime:
            prefix = mime.split("/")[0]
            if prefix == "image":     return "Image"
            if prefix == "audio":     return "Audio"
            if prefix == "video":     return "Video"
            if prefix in ("text", "application"):
                # Heuristic: try to read as text; if it succeeds treat as Code
                try:
                    path.read_text(encoding="utf-8")
                    return "Code"
                except UnicodeDecodeError:
                    return "Document"

        raise ValueError(
            f"Unsupported file type: '{ext}' (MIME: {mime}). "
            "Add the extension to DataRouter's mapping or preprocess manually."
        )


# ══════════════════════════════════════════════════════════════════════════════
#  MARKDOWN UNIFIER
# ══════════════════════════════════════════════════════════════════════════════

class MarkdownUnifier:
    """
    Prepends a strict YAML-style metadata block to any raw Markdown.

    The metadata block makes every chunk self-describing and is critical for
    the retrieval stage: it lets the vector store filter by source, modality,
    or ingestion time without having to decode chunk content.

    Metadata fields
    ---------------
    Source    : original filename
    Modality  : "Document" | "Audio" | "Image" | "Video" | "Code"
    Timestamp : ISO-8601 UTC ingestion time
    """

    HEADER_TEMPLATE = """\
---
Source    : {source}
Modality  : {modality}
Timestamp : {timestamp}
---

"""

    def unify(
        self,
        markdown: str,
        source: str | Path,
        modality: str,
    ) -> str:
        """
        Prepend metadata to *markdown* and return the unified document.

        Parameters
        ----------
        markdown  : str
            Raw Markdown string produced by a processor.
        source    : str | Path
            Original filename or path (only the filename is stored).
        modality  : str
            Modality label from DataRouter.
        """
        timestamp = datetime.now(tz=timezone.utc).isoformat(timespec="seconds")
        source_name = Path(source).name

        header = self.HEADER_TEMPLATE.format(
            source=source_name,
            modality=modality,
            timestamp=timestamp,
        )

        unified = header + markdown.strip() + "\n"
        logger.info(
            "[MarkdownUnifier] Header applied — source='%s', modality='%s'",
            source_name,
            modality,
        )
        return unified


# ══════════════════════════════════════════════════════════════════════════════
#  CHUNKING — type alias
# ══════════════════════════════════════════════════════════════════════════════

# Type alias for a single chunk
ChunkDict = dict[str, Union[str, list[str]]]


# ══════════════════════════════════════════════════════════════════════════════
#  MARKDOWN CHUNKER — deterministic, structure-aware (the new default)
# ══════════════════════════════════════════════════════════════════════════════

class MarkdownChunker:
    """
    Deterministic Markdown-aware chunker — no LLM call, no JSON parsing.

    Walks the document as a stream of *structural blocks* (headings,
    paragraphs, fenced code, tables, blockquotes, lists) and packs them into
    chunks of roughly TARGET_CHARS, preferring heading boundaries as natural
    split points. Atomic blocks (code, tables, blockquotes) are NEVER split
    across chunks. Each chunk is prepended with its heading outline so it
    remains self-contained out of context.

    WHY THIS REPLACES THE LLM CHUNKER AS DEFAULT
    ────────────────────────────────────────────
    The previous default (`ChunkingAgent`) asked Llama 3 to emit the whole
    document as a JSON array in one call. That had three real problems:

      1. Fragile: the model occasionally returned malformed JSON on long
         inputs, raising ProcessingError and killing the ingest.
      2. Silent truncation: anything past num_ctx (8192 tokens) was lost.
      3. Lossy: the model sometimes paraphrased chunk_text instead of copying
         it verbatim, so stored chunks drifted from the source.

    This chunker is:
      • ~200× faster (no LLM call — <100ms vs ~20s per document)
      • Verbatim: every chunk_text is an exact substring of the input
      • Bounded: predictable chunk size regardless of document length

    `ChunkingAgent` is still available as an opt-in alternative via
    MultimodalRAGPipeline(chunker_strategy="llm").

    NOTE ON summary / keywords
    ──────────────────────────
    These fields are emitted as empty strings/lists. The retrieval pipeline
    embeds `contextualized_text` and BM25-indexes it too — summary and
    keywords are stored only as Chroma metadata and are never used at query
    time. Leaving them empty has no impact on retrieval quality.
    """

    #: Target chunk size in characters (≈ 350 tokens at ~4 chars/token).
    TARGET_CHARS = 1500
    #: Hard upper bound — only exceeded when a single atomic block is bigger.
    MAX_CHARS    = 3000
    #: Below this, a trailing chunk is merged backwards into its predecessor.
    MIN_CHARS    = 250

    # Regex helpers
    _RE_FENCE     = re.compile(r"^(```|~~~)")
    _RE_HEADING   = re.compile(r"^(#{1,6})\s+(.*)$")
    _RE_TABLE_ROW = re.compile(r"^\s*\|")
    _RE_QUOTE     = re.compile(r"^\s*>")
    _RE_YAML      = re.compile(r"^---\s*$")

    # ── Public API ────────────────────────────────────────────────────────────

    def chunk(self, unified_markdown: str) -> list[ChunkDict]:
        """
        Split *unified_markdown* into a list of ChunkDicts.

        The Markdown is expected to have an optional YAML metadata header
        (between `---` markers) at the very top — that block is stripped
        before chunking because source/modality/timestamp are already
        stored on each chunk as proper metadata.
        """
        if not unified_markdown or not unified_markdown.strip():
            return []

        body = self._strip_yaml_header(unified_markdown)
        blocks = self._tokenize(body)
        chunks = self._pack(blocks)

        # Filter empties just in case
        result: list[ChunkDict] = []
        for text in chunks:
            text = text.strip()
            if text:
                result.append({
                    "chunk_text": text,
                    "summary"   : "",       # populated downstream if ever needed
                    "keywords"  : [],
                })
        logger.info("[MarkdownChunker] Produced %d chunks from %d blocks.",
                    len(result), len(blocks))
        return result

    # ── Stage 1: strip YAML metadata header ──────────────────────────────────

    def _strip_yaml_header(self, text: str) -> str:
        """If the document starts with `---\\n...\\n---`, drop it."""
        lines = text.splitlines(keepends=True)
        if not lines or not self._RE_YAML.match(lines[0].strip()):
            return text
        # Find the closing `---`
        for i in range(1, len(lines)):
            if self._RE_YAML.match(lines[i].strip()):
                return "".join(lines[i + 1:]).lstrip()
        return text  # malformed — leave intact

    # ── Stage 2: tokenize into structural blocks ─────────────────────────────

    def _tokenize(self, text: str) -> list[dict]:
        """
        Walk the document line-by-line, grouping consecutive lines into
        structural blocks. Each block dict has:
            kind   : "heading" | "code" | "table" | "quote" | "paragraph"
            level  : int (heading depth, else 0)
            text   : str (block content WITH trailing newline)
        """
        blocks: list[dict] = []
        lines = text.splitlines()
        i = 0
        n = len(lines)

        while i < n:
            line = lines[i]
            stripped = line.strip()

            # Blank line — paragraph separator
            if not stripped:
                i += 1
                continue

            # Fenced code block — atomic
            if self._RE_FENCE.match(stripped):
                start = i
                fence = stripped[:3]
                i += 1
                while i < n and not lines[i].strip().startswith(fence):
                    i += 1
                if i < n:
                    i += 1  # consume closing fence
                blocks.append({
                    "kind": "code", "level": 0,
                    "text": "\n".join(lines[start:i]) + "\n",
                })
                continue

            # Heading
            m = self._RE_HEADING.match(line)
            if m:
                blocks.append({
                    "kind" : "heading",
                    "level": len(m.group(1)),
                    "text" : line + "\n",
                })
                i += 1
                continue

            # Table — consecutive lines starting with `|`
            if self._RE_TABLE_ROW.match(line):
                start = i
                while i < n and self._RE_TABLE_ROW.match(lines[i]):
                    i += 1
                blocks.append({
                    "kind": "table", "level": 0,
                    "text": "\n".join(lines[start:i]) + "\n",
                })
                continue

            # Blockquote — consecutive `>` lines
            if self._RE_QUOTE.match(line):
                start = i
                while i < n and self._RE_QUOTE.match(lines[i]):
                    i += 1
                blocks.append({
                    "kind": "quote", "level": 0,
                    "text": "\n".join(lines[start:i]) + "\n",
                })
                continue

            # Paragraph — until next blank line or structural break
            start = i
            while (
                i < n
                and lines[i].strip()
                and not self._RE_FENCE.match(lines[i].strip())
                and not self._RE_HEADING.match(lines[i])
                and not self._RE_TABLE_ROW.match(lines[i])
                and not self._RE_QUOTE.match(lines[i])
            ):
                i += 1
            blocks.append({
                "kind": "paragraph", "level": 0,
                "text": "\n".join(lines[start:i]) + "\n",
            })

        return blocks

    # ── Stage 3: pack blocks into target-sized chunks ────────────────────────

    def _pack(self, blocks: list[dict]) -> list[str]:
        """
        Greedy packer:
          • Track the current heading outline (parent chain).
          • Accumulate blocks until we cross TARGET_CHARS.
          • Prefer to emit at heading boundaries — when we hit a new heading
            and the buffer is already past TARGET/2, flush.
          • Never split an atomic block (code/table/quote): if a single block
            blows past MAX_CHARS, emit it on its own and continue.
          • Split very long paragraphs at sentence boundaries.

        ── Outline semantics ──────────────────────────────────────────────
        Each emitted chunk may be prepended with an "outline" — a Markdown
        breadcrumb of the parent headings ABOVE the chunk's content. This
        only happens for chunks that start mid-section (no leading heading
        of their own); chunks that begin with a heading already announce
        their location and need no extra prefix. Outline is captured at the
        moment a buffer starts so it reflects the chunk's actual context,
        not whatever the heading state happens to be at flush time.
        """
        chunks: list[str] = []
        buf: list[str] = []
        buf_len = 0
        # Heading stack: indexed 0..5 for h1..h6. Empty string means "no heading
        # at this level yet".
        heading_stack: list[str] = ["" for _ in range(6)]
        # Outline snapshot at the moment the CURRENT buffer started.
        # Empty when the buffer leads with its own heading.
        outline_at_start = ""

        def outline() -> str:
            return "\n".join(h for h in heading_stack if h)

        def flush(force: bool = False) -> None:
            nonlocal buf, buf_len, outline_at_start
            if not buf:
                return
            body = "".join(buf).strip()
            # Merge tiny tail chunks into the previous one rather than emit
            # an under-sized standalone chunk.
            if not force and len(body) < self.MIN_CHARS and chunks:
                chunks[-1] = chunks[-1].rstrip() + "\n\n" + body + "\n"
            else:
                text = (outline_at_start + "\n\n" + body) if outline_at_start else body
                chunks.append(text + "\n")
            buf, buf_len = [], 0
            outline_at_start = ""  # next chunk re-captures on its first block

        for block in blocks:
            kind = block["kind"]
            text = block["text"]
            tlen = len(text)

            if kind == "heading":
                lvl = block["level"]
                # Heading boundary: emit a chunk if the buffer is already
                # reasonably full; a new heading is the cleanest split point.
                if buf_len >= self.TARGET_CHARS // 2:
                    flush(force=True)
                # The new buffer leads with this heading → no outline prefix
                # needed; the heading is INSIDE the chunk.
                heading_stack[lvl - 1] = text.rstrip()
                for j in range(lvl, 6):
                    heading_stack[j] = ""
                buf.append(text)
                buf_len += tlen
                continue

            # Non-heading block. If this is the first block of a fresh buffer,
            # capture the current heading outline so the reader knows where
            # this orphaned content lives.
            if buf_len == 0:
                outline_at_start = outline()

            # Atomic blocks: never split. If adding it overflows MAX, flush first.
            atomic = kind in ("code", "table", "quote")
            if atomic and buf_len > 0 and buf_len + tlen > self.MAX_CHARS:
                flush(force=True)
                if buf_len == 0:
                    outline_at_start = outline()

            # Oversized paragraph — split on sentence boundaries.
            if kind == "paragraph" and tlen > self.MAX_CHARS:
                if buf_len > 0:
                    flush(force=True)
                if buf_len == 0:
                    outline_at_start = outline()
                for piece in self._split_long_paragraph(text):
                    buf.append(piece)
                    buf_len += len(piece)
                    if buf_len >= self.TARGET_CHARS:
                        flush(force=True)
                        if buf_len == 0:
                            outline_at_start = outline()
                continue

            buf.append(text)
            buf_len += tlen
            if buf_len >= self.TARGET_CHARS:
                flush(force=True)

        flush(force=True)
        return chunks

    # ── Helpers ──────────────────────────────────────────────────────────────

    @staticmethod
    def _split_long_paragraph(text: str) -> list[str]:
        """Split an oversized paragraph at sentence boundaries (. ! ?)."""
        parts = re.split(r"(?<=[.!?])\s+", text.strip())
        pieces, buf = [], ""
        for p in parts:
            candidate = (buf + " " + p).strip() if buf else p
            if len(candidate) > MarkdownChunker.TARGET_CHARS and buf:
                pieces.append(buf + "\n")
                buf = p
            else:
                buf = candidate
        if buf:
            pieces.append(buf + "\n")
        return pieces


# ══════════════════════════════════════════════════════════════════════════════
#  CHUNKING AGENT  (legacy LLM chunker — opt-in via chunker_strategy="llm")
# ══════════════════════════════════════════════════════════════════════════════

class ChunkingAgent:
    """
    Agentic chunker powered by a local **Llama 3** model via **Ollama**.

    Unlike naive fixed-size chunking, agentic chunking asks the LLM to
    identify semantically coherent segments based on topic shifts, logical
    boundaries, and section headers — producing chunks that are much more
    retrieval-friendly.

    Each chunk contains:
      • chunk_text : the raw Markdown slice (preserving context)
      • summary    : a 1–2 sentence dense summary for bi-encoder retrieval
      • keywords   : 5–10 keywords for sparse (BM25) retrieval

    Install : pip install ollama
    Setup   : ollama pull llama3
    """

    MODEL = "llama3"

    # ── System prompt ─────────────────────────────────────────────────────────
    # This prompt is the "brain" of the chunking strategy.  It instructs the
    # model to act as a document analyst rather than a text generator, and to
    # output ONLY structured JSON so the response can be parsed deterministically.
    SYSTEM_PROMPT = """\
You are an expert document analyst specializing in preparing text for \
Retrieval-Augmented Generation (RAG) systems.

Your task is to segment the provided Markdown document into semantically \
coherent chunks that will be stored in a vector database and retrieved to \
answer user questions.

CHUNKING RULES
--------------
1. Identify natural topic boundaries (e.g., heading changes, paragraph \
   breaks, logical transitions, speaker turns in transcripts, frame \
   timestamps in video analyses).
2. Each chunk MUST be self-contained: a reader with no surrounding context \
   should be able to understand it.
3. Aim for 150–400 tokens per chunk. If a section is very long, split it at \
   the most natural logical sub-boundary. If a section is very short, merge \
   it with the adjacent section that is most topically related.
4. NEVER split a code block, table, or blockquote across chunks.
5. Preserve the original Markdown formatting within chunk_text.
6. The metadata block at the top (between --- markers) MUST be included \
   verbatim in EVERY chunk so each chunk is self-describing.

OUTPUT FORMAT
-------------
Respond ONLY with a valid JSON array. Do NOT include any preamble, \
explanation, markdown fences, or trailing text.

Each element of the array must be a JSON object with exactly these keys:

  "chunk_text" : string  — the full Markdown slice including metadata header
  "summary"    : string  — a dense 1-2 sentence summary of this chunk's \
                           content (optimised for semantic similarity search)
  "keywords"   : array   — 5 to 10 lowercase keyword strings for BM25 \
                           sparse retrieval (avoid stopwords)

Example of correct output format (abbreviated):
[
  {
    "chunk_text": "---\\nSource: report.pdf\\n...\\n---\\n## Introduction\\n...",
    "summary": "Overview of the company's Q3 revenue performance and key drivers.",
    "keywords": ["revenue", "q3", "performance", "growth", "earnings"]
  },
  {
    "chunk_text": "---\\nSource: report.pdf\\n...\\n---\\n## Risk Factors\\n...",
    "summary": "Description of supply-chain and regulatory risks facing the company.",
    "keywords": ["risk", "supply chain", "regulation", "exposure", "mitigation"]
  }
]
"""

    def __init__(self, model: str = MODEL) -> None:
        self._model = model

    def chunk(self, unified_markdown: str) -> list[ChunkDict]:
        """
        Send *unified_markdown* to Llama 3 and return a list of chunk dicts.

        Parameters
        ----------
        unified_markdown : str
            Output of MarkdownUnifier.unify() — metadata header + content.

        Returns
        -------
        list[ChunkDict]
            Parsed JSON array from the model, each element containing
            'chunk_text', 'summary', and 'keywords'.

        Raises
        ------
        BaseProcessor.ProcessingError
            If the Ollama call fails or the model returns unparseable JSON.
        """
        logger.info(
            "[ChunkingAgent] Sending %d chars to %s for agentic chunking…",
            len(unified_markdown),
            self._model,
        )

        try:
            import ollama  # type: ignore
        except ImportError as exc:
            raise BaseProcessor.ProcessingError(
                "ollama is not installed. Run: pip install ollama"
            ) from exc

        try:
            response = ollama.chat(
                model=self._model,
                messages=[
                    {"role": "system", "content": self.SYSTEM_PROMPT},
                    {"role": "user",   "content": unified_markdown},
                ],
                options={
                    "temperature": 0.0,   # deterministic output — critical for JSON parsing
                    "num_ctx"    : 8192,  # increase if your documents are very long
                },
            )
        except Exception as exc:
            raise BaseProcessor.ProcessingError(
                f"Ollama/{self._model} call failed: {exc}. "
                "Ensure 'ollama serve' is running and 'ollama pull llama3' was executed."
            ) from exc

        raw: str = response["message"]["content"].strip()
        return self._parse_chunks(raw)

    # ── JSON parsing helpers ─────────────────────────────────────────────────

    def _parse_chunks(self, raw: str) -> list[ChunkDict]:
        """
        Robustly parse the model's response as a JSON array.

        LLMs occasionally wrap JSON in markdown fences or add preamble text
        despite explicit instructions.  This method strips common artefacts
        before attempting to parse.
        """
        # 1. Strip common markdown fences: ```json ... ``` or ``` ... ```
        cleaned = re.sub(r"^```(?:json)?\s*", "", raw, flags=re.IGNORECASE)
        cleaned = re.sub(r"\s*```$", "", cleaned).strip()

        # 2. Attempt direct parse
        try:
            chunks = json.loads(cleaned)
        except json.JSONDecodeError:
            # 3. Try to extract the first [...] block if there's surrounding prose
            match = re.search(r"\[.*\]", cleaned, flags=re.DOTALL)
            if match:
                try:
                    chunks = json.loads(match.group())
                except json.JSONDecodeError as exc:
                    raise BaseProcessor.ProcessingError(
                        f"ChunkingAgent: model returned unparseable JSON.\n"
                        f"Raw response (first 500 chars):\n{raw[:500]}"
                    ) from exc
            else:
                raise BaseProcessor.ProcessingError(
                    "ChunkingAgent: model response contains no JSON array.\n"
                    f"Raw response (first 500 chars):\n{raw[:500]}"
                )

        if not isinstance(chunks, list):
            raise BaseProcessor.ProcessingError(
                f"ChunkingAgent: expected JSON array, got {type(chunks).__name__}."
            )

        # 4. Validate and normalise each chunk
        validated: list[ChunkDict] = []
        for i, chunk in enumerate(chunks):
            if not isinstance(chunk, dict):
                logger.warning("[ChunkingAgent] Skipping non-dict item at index %d", i)
                continue

            validated.append({
                "chunk_text" : str(chunk.get("chunk_text", "")),
                "summary"    : str(chunk.get("summary", "")),
                "keywords"   : list(chunk.get("keywords", [])),
            })

        logger.info("[ChunkingAgent] Parsed %d chunks.", len(validated))
        return validated


# ══════════════════════════════════════════════════════════════════════════════
#  CONTEXTUAL RETRIEVER  (Anthropic-style contextual retrieval, local edition)
# ══════════════════════════════════════════════════════════════════════════════

class ContextualRetriever:
    """
    Enriches each chunk with a *situating context* generated by a local LLM
    that has access to the **entire source document**.

    ── Why this matters ────────────────────────────────────────────────────────
    When a chunk is embedded and stored in a vector DB, it loses the document-
    level context that makes it interpretable.  A chunk like:

        "Revenue declined by 12 % quarter-over-quarter."

    is ambiguous: which company? which quarter? which product line?

    The contextual retrieval technique fixes this by prepending a short,
    LLM-generated situating sentence BEFORE the chunk text:

        "This chunk is from the Q3 2024 earnings report of Acme Corp,
         specifically the section on North American retail segment performance.
         Revenue declined by 12 % quarter-over-quarter."

    The enriched text (context + chunk) is what gets embedded and what BM25
    indexes.  The original chunk_text is preserved separately for display.

    ── Parallelism ─────────────────────────────────────────────────────────────
    Each chunk requires one LLM call.  These are independent, so they run
    concurrently via `ThreadPoolExecutor`.  For a 20-chunk document with a
    ~1 s/call local model, wall time drops from ~20 s → ~3–5 s (depending on
    Ollama's concurrency setting and GPU VRAM).

    ── Output fields added to each ChunkDict ───────────────────────────────────
      context             : str  — the raw 1–2 sentence situating context
      contextualized_text : str  — context prepended to chunk_text
                                   (this is what you embed and BM25-index)

    Install : pip install ollama  (already required)
    Setup   : ollama pull llama3  (already required)
    """

    MODEL = "llama3"

    # Maximum number of parallel Ollama calls.
    # Keep ≤ 4 for CPU-only; raise to 8–16 with a GPU that has enough VRAM.
    DEFAULT_MAX_WORKERS = 4

    # ── Prompt templates ─────────────────────────────────────────────────────
    # These follow Anthropic's published prompt structure for contextual
    # retrieval almost verbatim, adapted for local Llama 3.

    SYSTEM_PROMPT = (
        "You are a precision document analyst assisting with the preparation "
        "of a Retrieval-Augmented Generation (RAG) knowledge base. "
        "You will be given a full document and a specific chunk of that document. "
        "Your ONLY job is to write a SHORT situating context (1–2 sentences, "
        "≤ 60 words) that places the chunk within the broader document so a "
        "reader encountering the chunk in complete isolation would understand "
        "what document it came from, what section it belongs to, and what "
        "higher-level concept it relates to.\n\n"
        "OUTPUT RULES:\n"
        "- Output ONLY the context sentence(s). No preamble, no labels, "
        "  no 'Here is the context:', no quotation marks around your answer.\n"
        "- Never summarise the chunk itself — only situate it.\n"
        "- Write in the third person, present tense.\n"
        "- Be specific: name the document, section, or topic explicitly."
    )

    USER_TEMPLATE = (
        "<document>\n"
        "{full_document}\n"
        "</document>\n\n"
        "Here is the specific chunk that needs to be situated:\n\n"
        "<chunk>\n"
        "{chunk_text}\n"
        "</chunk>\n\n"
        "Write the situating context now:"
    )

    def __init__(
        self,
        model: str = MODEL,
        max_workers: int = DEFAULT_MAX_WORKERS,
    ) -> None:
        self._model       = model
        self._max_workers = max_workers

    # ── Public API ────────────────────────────────────────────────────────────

    def enrich(
        self,
        chunks: list[ChunkDict],
        full_document: str,
    ) -> list[ChunkDict]:
        """
        Enrich every chunk in *chunks* with a situating context.

        Parameters
        ----------
        chunks : list[ChunkDict]
            Output of ChunkingAgent.chunk() — list of dicts with at least
            a 'chunk_text' key.
        full_document : str
            The complete unified Markdown document (metadata header + content).
            Passed to the LLM on every call so it can situate each chunk.

        Returns
        -------
        list[ChunkDict]
            Same list, each dict extended with:
              'context'             — the generated situating sentence(s)
              'contextualized_text' — context + "\\n\\n" + chunk_text
              'context_error'       — present only if contextualisation failed;
                                      the chunk is still returned unmodified.
        """
        if not chunks:
            return chunks

        logger.info(
            "[ContextualRetriever] Enriching %d chunks with situating context "
            "(model=%s, workers=%d)…",
            len(chunks),
            self._model,
            self._max_workers,
        )

        enriched: list[ChunkDict] = [{}] * len(chunks)  # pre-allocate slots

        with ThreadPoolExecutor(max_workers=self._max_workers) as pool:
            # Submit one future per chunk, carrying the original index so we
            # can reassemble in order after parallel completion.
            future_to_idx = {
                pool.submit(
                    self._contextualise_one,
                    chunk,
                    full_document,
                    idx,
                ): idx
                for idx, chunk in enumerate(chunks)
            }

            for future in as_completed(future_to_idx):
                idx = future_to_idx[future]
                try:
                    enriched[idx] = future.result()
                except Exception as exc:
                    # A single chunk failure must NOT abort the whole batch.
                    logger.warning(
                        "[ContextualRetriever] Chunk %d failed: %s — "
                        "returning original chunk without context.",
                        idx,
                        exc,
                    )
                    original = dict(chunks[idx])
                    original["context"]             = ""
                    original["contextualized_text"] = str(original.get("chunk_text", ""))
                    original["context_error"]        = str(exc)
                    enriched[idx]                    = original

        succeeded = sum(1 for c in enriched if "context_error" not in c)
        logger.info(
            "[ContextualRetriever] Done — %d/%d chunks successfully contextualised.",
            succeeded,
            len(chunks),
        )
        return enriched

    # ── Internal helpers ──────────────────────────────────────────────────────

    def _contextualise_one(
        self,
        chunk: ChunkDict,
        full_document: str,
        idx: int,
    ) -> ChunkDict:
        """
        Generate a situating context for a single chunk and return an
        enriched copy of the chunk dict.

        This method is called from a thread pool, so it must be thread-safe.
        The `ollama` library uses its own HTTP session per call, which is safe.
        """
        try:
            import ollama  # type: ignore
        except ImportError as exc:
            raise BaseProcessor.ProcessingError(
                "ollama is not installed. Run: pip install ollama"
            ) from exc

        chunk_text = str(chunk.get("chunk_text", ""))

        user_message = self.USER_TEMPLATE.format(
            full_document=full_document,
            chunk_text=chunk_text,
        )

        logger.debug("[ContextualRetriever] Contextualising chunk %d…", idx)

        try:
            response = ollama.chat(
                model=self._model,
                messages=[
                    {"role": "system", "content": self.SYSTEM_PROMPT},
                    {"role": "user",   "content": user_message},
                ],
                options={
                    # Slight creativity (0.2) produces more natural phrasing
                    # than fully deterministic (0.0) for short prose sentences.
                    "temperature": 0.2,
                    # Context window: full_document + chunk.
                    # Increase if documents exceed ~6 000 tokens.
                    "num_ctx": 8192,
                },
            )
        except Exception as exc:
            raise BaseProcessor.ProcessingError(
                f"Ollama call failed for chunk {idx}: {exc}"
            ) from exc

        context: str = response["message"]["content"].strip()

        if not context:
            raise BaseProcessor.ProcessingError(
                f"LLM returned empty context for chunk {idx}."
            )

        # Build the enriched chunk: copy all existing keys and add new ones.
        enriched = dict(chunk)
        enriched["context"] = context
        # This is what gets embedded — context first, then the chunk itself.
        enriched["contextualized_text"] = f"{context}\n\n{chunk_text}"

        logger.debug(
            "[ContextualRetriever] Chunk %d contextualised (%d chars context).",
            idx,
            len(context),
        )
        return enriched




class MultimodalRAGPipeline:
    """
    High-level orchestrator that wires:

        DataRouter → MarkdownUnifier → ChunkingAgent → ContextualRetriever

    into a single `ingest()` call.

    The `contextual_retrieval` flag (default: True) controls whether the
    ContextualRetriever step runs.  Disable it to reproduce v1.0 behaviour or
    to benchmark the improvement contextual retrieval provides.

    Usage
    -----
    >>> pipeline = MultimodalRAGPipeline()
    >>> chunks = pipeline.ingest("quarterly_report.pdf")
    >>> for c in chunks:
    ...     print(c["context"])              # situating sentence  ← NEW
    ...     print(c["contextualized_text"])  # what gets embedded  ← NEW
    ...     print(c["summary"])
    ...     print(c["keywords"])
    """

    def __init__(
        self,
        whisper_model       : str  = AudioProcessor.DEFAULT_MODEL,
        llava_model         : str  = ImageProcessor.DEFAULT_MODEL,
        llama_model         : str  = ChunkingAgent.MODEL,
        keyframe_interval   : int  = VideoProcessor.DEFAULT_KEYFRAME_INTERVAL,
        contextual_retrieval: bool = True,
        context_max_workers : int  = ContextualRetriever.DEFAULT_MAX_WORKERS,
        chunker_strategy    : str  = "markdown",   # "markdown" (default) or "llm"
    ) -> None:
        self._router  = DataRouter(
            whisper_model=whisper_model,
            llava_model=llava_model,
            keyframe_interval=keyframe_interval,
        )
        self._unifier = MarkdownUnifier()

        # Chunker selection. "markdown" is the new default — deterministic,
        # ~200× faster, immune to JSON parse failures, verbatim chunks.
        # "llm" preserves the original ChunkingAgent for users who want it.
        if chunker_strategy == "llm":
            self._chunker = ChunkingAgent(model=llama_model)
            logger.info("[MultimodalRAGPipeline] Using LLM chunker (legacy).")
        else:
            self._chunker = MarkdownChunker()
            logger.info("[MultimodalRAGPipeline] Using deterministic Markdown chunker.")

        self._url_proc = URLProcessor()

        self._use_contextual = contextual_retrieval
        self._ctx_retriever  = (
            ContextualRetriever(model=llama_model, max_workers=context_max_workers)
            if contextual_retrieval
            else None
        )

    def _chunk_and_enrich(
        self,
        unified: str,
        source_name: str,
        modality: str,
    ) -> list[ChunkDict]:
        """
        Shared tail of the pipeline: agentic chunking → metadata stamping →
        optional contextual enrichment. Used by both ingest() and ingest_url().
        """
        chunks = self._chunker.chunk(unified)

        # Attach source name + modality so downstream metadata filters work.
        for chunk in chunks:
            chunk["source"]   = source_name
            chunk["modality"] = modality

        if self._use_contextual and self._ctx_retriever is not None:
            chunks = self._ctx_retriever.enrich(chunks, full_document=unified)
        return chunks

    def ingest(self, file_path: str | Path) -> list[ChunkDict]:
        """
        Full pipeline: file → context-enriched chunks.

        Parameters
        ----------
        file_path : str | Path
            Any supported file (document, audio, image, video, code).

        Returns
        -------
        list[ChunkDict]
            Ready-to-index chunks.  Each dict contains:

            Always present
            ~~~~~~~~~~~~~~
            chunk_text          : str        original Markdown slice
            summary             : str        dense retrieval summary
            keywords            : list[str]  BM25 keywords

            Present when contextual_retrieval=True (default)
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            context             : str        situating 1–2 sentences
            contextualized_text : str        context + chunk_text  ← EMBED THIS
            context_error       : str        only if contextualisation failed
        """
        path = Path(file_path)
        logger.info("═══ Pipeline start: '%s' ═══", path.name)

        # Step 1: Route → raw Markdown
        raw_markdown, modality = self._router.route(path)

        # Step 2: Unify → metadata header + Markdown
        unified = self._unifier.unify(
            markdown=raw_markdown,
            source=path,
            modality=modality,
        )

        # Steps 3–4: chunk, stamp metadata, contextual enrichment
        chunks = self._chunk_and_enrich(unified, source_name=path.name, modality=modality)

        logger.info(
            "═══ Pipeline complete: '%s' → %d chunks ═══",
            path.name,
            len(chunks),
        )
        return chunks

    def ingest_url(self, url: str) -> tuple[list[ChunkDict], str]:
        """
        Full pipeline for a web page: URL → context-enriched chunks.

        Returns
        -------
        (chunks, source_name)
            source_name is the page title (used as the 'source' in metadata).
        """
        logger.info("═══ Pipeline start (URL): '%s' ═══", url)

        # Step 1: Fetch + extract clean Markdown
        raw_markdown, title = self._url_proc.process(url)

        # Use a stable, human-readable source name. Prefer the page title;
        # fall back to the URL. Keep it short for clean display/citation.
        source_name = (title or url).strip()[:120]

        # Step 2: Unify → metadata header + Markdown (modality = "Web")
        unified = self._unifier.unify(
            markdown=raw_markdown,
            source=source_name,
            modality="Web",
        )

        # Steps 3–4: chunk, stamp metadata, contextual enrichment
        chunks = self._chunk_and_enrich(unified, source_name=source_name, modality="Web")

        logger.info(
            "═══ Pipeline complete (URL): '%s' → %d chunks ═══",
            source_name,
            len(chunks),
        )
        return chunks, source_name


# ══════════════════════════════════════════════════════════════════════════════
#  CLI / DEMO ENTRY POINT
# ══════════════════════════════════════════════════════════════════════════════

def main() -> None:
    """
    Minimal command-line interface for the pipeline.

    Usage
    -----
      python multimodal_rag_pipeline.py <file_path> [output.json] [--no-context]

    Flags
    -----
      --no-context   Disable contextual retrieval (v1.0 behaviour).
                     Use this to benchmark the improvement CR provides.

    If no output path is given, results are printed to stdout.
    """
    import sys

    args = sys.argv[1:]

    # Parse --no-context flag
    use_context = True
    if "--no-context" in args:
        args.remove("--no-context")
        use_context = False

    if not args:
        print(
            "Usage: python multimodal_rag_pipeline.py <file_path> [output.json] [--no-context]\n\n"
            "Examples:\n"
            "  python multimodal_rag_pipeline.py report.pdf\n"
            "  python multimodal_rag_pipeline.py meeting.mp3 chunks.json\n"
            "  python multimodal_rag_pipeline.py diagram.png\n"
            "  python multimodal_rag_pipeline.py lecture.mp4 lecture_chunks.json\n"
            "  python multimodal_rag_pipeline.py main.py code_chunks.json\n"
            "  python multimodal_rag_pipeline.py report.pdf out.json --no-context\n"
        )
        sys.exit(1)

    file_path   = Path(args[0])
    output_path = Path(args[1]) if len(args) > 1 else None

    pipeline = MultimodalRAGPipeline(contextual_retrieval=use_context)

    try:
        chunks = pipeline.ingest(file_path)
    except FileNotFoundError as exc:
        logger.error("File not found: %s", exc)
        sys.exit(2)
    except BaseProcessor.ProcessingError as exc:
        logger.error("Processing failed: %s", exc)
        sys.exit(3)
    except Exception as exc:
        logger.exception("Unexpected error: %s", exc)
        sys.exit(4)

    json_output = json.dumps(chunks, indent=2, ensure_ascii=False)

    if output_path:
        output_path.write_text(json_output, encoding="utf-8")
        logger.info("Chunks written to '%s'", output_path)

        # Print a quick human-readable summary to stdout
        for i, chunk in enumerate(chunks, 1):
            ctx = chunk.get("context", "(contextual retrieval disabled)")
            kws = ", ".join(chunk.get("keywords", []))
            print(f"\n── Chunk {i} ──")
            print(f"  Context  : {ctx}")
            print(f"  Summary  : {chunk.get('summary', '')}")
            print(f"  Keywords : {kws}")
    else:
        print(json_output)


if __name__ == "__main__":
    main()
